version: "2"

linters:
  default: standard
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - embeddedstructfieldcheck
    - errname
    - errorlint
    - errorlint
    - exhaustive
#    - exhaustruct
    - exptostd
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - intrange
    - iotamixing
#    - noctx
    - reassign
    - recvcheck
#    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - unconvert
  disable:
    - lll

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - blank
        - dot
        - default
        - localmodule
      custom-order: true
    gofumpt:
      module-path: github.com/treyburn/lockbox
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/treyburn/lockbox