version: "2"

linters:
  default: standard
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - embeddedstructfieldcheck
    - errname
    - errorlint
    - errorlint
    - exhaustive
#    - exhaustruct
    - exptostd
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - intrange
    - iotamixing
#    - noctx
    - reassign
    - recvcheck
#    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - unconvert
  disable:
    - lll

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/treyburn/lockbox